### ISSUE TITLE
yar-java  项目目前是什么状态？

### ISSUE THREAD

**Issue by gyf19** [weibocom/yar-java#1]
yar-java  项目目前是什么状态？   测试版本还是 正式版本？

**Comment by gyf19** [comment]
@rayzhang0603  你好！

**Comment by rayzhang0603** [comment]
正式版本。目前微博运动等业务在使用中。

**Comment by gyf19** [comment]
@rayzhang0603   server 支持长连接 socket 通信吗？

**Comment by rayzhang0603** [comment]
不支持socket长链。yar协议是建立在http协议上的。不过可以支持keepalive

**Comment by gyf19** [comment]
@rayzhang0603   不好意思，今天才回消息。  yar协议 也是可以使用到socket 长链。  yar-c, yar-go 已经支持 socket长链了,  我是yar-go 作者。   不知道你们有没计划支持一下 socket 长链。

**Comment by rayzhang0603** [comment]
由于目前需要支持motan新功能开发，暂时没有yar-java的开发计划。
